### ISSUE TITLE
Not working on macOS/Chrome

### ISSUE THREAD

**Issue by realmayus** [djipco/webmidi#111] opened 2020-05-20 13:44 UTC
I am using Google Chrome on the latest version of macOS.
I get this error:
`Error: the WebMIDI API is not supported by your browser`

It works on sites like the examples of tone.js: https://tonejs.github.io/examples/sampler.html
(this is the code they use: https://github.com/Tonejs/ui/blob/master/src/midi/midi-in.js)

I am using it in React in a function-based component. My Code: https://gist.github.com/9dcc83ce06ce94d19188064f9b3c3311

**Comment by djipco** [comment] 2020-05-20 17:09
I just tested it on Chrome v83 on macOS Catalina and it works fine for me. Can you tell me which version of Chrome and macOS you are using?

Also, if you had a code example to reproduce the problem, it may help me identify the source of the issue.

**Comment by djipco** [comment] 2020-06-04 13:27
Since it has been 15 days and I have received any more info, I will go ahead and close the issue. If you still have the problem and can provide more details, you can simply re-open this issue.

**Closed by djipco** 2020-06-04 13:27 UTC
Labels: Status: info needed
