### ISSUE TITLE
Module not found: Error: Can't resolve 'perf_hooks'

### ISSUE THREAD

**Issue by michaelcaterisano** [djipco/webmidi#137] opened 2021-04-13 15:00 UTC
**Describe the bug and how ro reproduce it**
Getting the following error when using v. 3.0:

`ERROR in ./node_modules/webmidi/dist/webmidi.esm.min.js
Module not found: Error: Can't resolve 'perf_hooks'`

**Environment:**
 - Operating system: Mac OS 10.15.7
 - Browser name and version (or Node.js version): Chrome Version 89.0.4389.114 (Official Build) (x86_64)
 - Library version: 3.0 alpha (installed webmidi@next via npm)

**Additional context**
Not sure! I love the library though and can't wait to try out the alpha version.

**Comment by michaelcaterisano** [comment] 2021-04-13 20:04
I'm using WebMidi.js v3.0.0-alpha.4

I'm using WebMidi in a lit-element project, and building the the project with webpack. WebMidi version 2.5.x works fine, but 3.0 doesn't. My webpack config looks like this:

```
const path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  devServer: {
    contentBase: path.resolve(__dirname),
    watchContentBase: true,
  },
  mode: "development",
  devtool: "source-map",
  module: {
    rules: [{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" }],
  },
};
```

**Comment by djipco** [comment] 2021-04-14 02:50
The `perf_hooks` module is only needed when WebMidi.js is being run in Node.js. Normally, it should have no impact on browser code. The problem is that Webpack performs its preprocessing in Node.js and, while it's doing that, triggers the loading of the module. 

To fix this issue, I am now stripping the code that loads the `perf_hooks` and `jzz` modules from the **IIFE** and **ESM** distributions. Hopefully, this will also fix the problem with server-side rendering reported in issue https://github.com/djipco/webmidi/issues/133. Version 3.0.0-alpha.5 contains the fix and is available now for installation.

Thanks a lot @michaelcaterisano for reporting the problem. This is why the library is still in alpha! Do you think you could try it out and let me know if it fixes the problem for you?

Cheers!

**Comment by henriquegmatos** [comment] 2021-04-14 12:29
Finally, this Perf_Hooks problem that I pointed out in # 120 was solved with alpha-5.

Thank you very much.

**Comment by michaelcaterisano** [comment] 2021-04-14 12:53
Version 3.0.0-alpha.5 works! Thanks @djipco!

**Comment by djipco** [comment] 2021-04-14 13:21
Thanks @henriquegmatos for reminding me. I think that the problem you described in issue #120 was not caused by Vue.js but rather by webpack. Is that possible?

In any case, I will close this issue since it seems to fix the problem. Cheers!

**Closed by djipco** 2021-04-14 13:21 UTC
Labels: Type: bug
