### ISSUE TITLE
Two of the same device not showing as separate outputs

### ISSUE THREAD

**Issue by tom-cartwright** [djipco/webmidi#81] opened 2019-05-15 15:11 UTC
I have two of the same device plugged into my PC. In the device manager, I see both devices (both with the same name) however a console log of `WebMidi.Outputs` only shows a single output and messages sent to this port only send to one device.

The program I am writing needs to be able to send a sysex message to multiple of the same device at the same time.

Is this a limitation of the API or am I missing something?

**Comment by djipco** [comment] 2019-05-15 20:58
Hmm... no sure. I'll try to replicate the problem tomorrow. I don't have two units of the same device right now. I'll keep you posted.

**Comment by TimSusa** [comment] 2019-05-18 13:05
@tom-cartwright Can you tell more about your hardware, please? I assume you have win installed? At a  first shot I would claim, it is not really ok from your OS to give the same name to different hardware, better second-name like first-name (+1) or so (I know, you are not responsible for this). Anyhow, the standard should provide us with an additional outputId for each driver slot. I would claim these Ids should be different...

You know, what you can do? Put that little code-snippet here in your browser console (should work natively with Chrome). It should provide you with every drivername and its outputId, which is natively found from the browser. If you can observe your second device in your console, it is probably a webmidi issue.

```  
var midi, data;
// start talking to MIDI controller
if (navigator.requestMIDIAccess) {
  navigator.requestMIDIAccess({
    sysex: false
  }).then(onMIDISuccess, onMIDIFailure);
} else {
  console.warn("No MIDI support in your browser")
  
}

// on success
function onMIDISuccess(midiData) {
  // this is all our MIDI data
  midi = midiData;
  var allInputs = midi.inputs.values();
  // loop over all available inputs and listen for any MIDI input
  for (var input = allInputs.next(); input && !input.done; input = allInputs.next()) {
    // when a MIDI value is received call the onMIDIMessage function

      console.log('input drivername ', input.value.name, ' inputId: ', input.value.id)
  }
  
  var allOuts = midi.outputs.values();
  for (var output = allOuts.next(); output && !output.done; output = allOuts.next()) {
    // when a MIDI value is received call the onMIDIMessage function

      console.log('output drivername ', output.value.name, ' outputId: ', output.value.id)
  }
}
// on failure
function onMIDIFailure() {
  console.warn("Not recognising MIDI controller")
}

``` 

<img width="1673" alt="Screenshot 2019-05-18 at 15 04 48" src="https://user-images.githubusercontent.com/8963529/57970155-4f03cc80-797e-11e9-8348-cf7bb93513a9.png">

**Comment by TimSusa** [comment] 2019-05-19 07:48
I had a short look to the headless tests, giving two identical input names and midi-test it seems to give the identical driver id out. I had a look into the C++ Code and it uses the native driver sdk for Mac here on my system, which looks now quite strange to me.

``` 
WebMIDI Headless Tests
    ✓ virtual-midi-in driver was created and found by webmidi (89ms)
out  Output {
  _midiOutput:
   MIDIOutput {
     type: 'output',
     name: 'Virtual MIDI-Out',
     manufacturer: 'Unknown',
     version: '0.0',
     id:
      '4F92FB7BF31481C4362B739254AF8FB6C9A912206E057A041740707B8766067A',
     state: 'disconnected',
     connection: 'closed' },
  connection: [Getter],
  id: [Getter],
  manufacturer: [Getter],
  name: [Getter],
  state: [Getter],
  type: [Getter] }
out2  Output {
  _midiOutput:
   MIDIOutput {
     type: 'output',
     name: 'Virtual MIDI-Out',
     manufacturer: 'Unknown',
     version: '0.0',
     id:
      '4F92FB7BF31481C4362B739254AF8FB6C9A912206E057A041740707B8766067A',
     state: 'disconnected',
     connection: 'closed' },
  connection: [Getter],
  id: [Getter],
  manufacturer: [Getter],
  name: [Getter],
```

**Comment by djipco** [comment] 2019-05-20 19:02
>In the device manager, I see both devices (both with the same name) however a console log of WebMidi.Outputs only shows a single output and messages sent to this port only send to one device.

I can replicate this. The device manager on Windows 10 shows both devices but only one is displayed at the Web MIDI API level. This can be confirmed by running the following code in the console (as suggested by @TimSusa): 

```javascript
navigator.requestMIDIAccess().then(onMIDISuccess, err => console.log(err));

function onMIDISuccess(midi) {
  let allInputs = midi.inputs.values();
  for (var input = allInputs.next(); input && !input.done; input = allInputs.next()) {
      console.log('Input ', input.value.name, ' id: ', input.value.id)
  }
}
```
If I do the same thing on macOS, I get the expected behaviour: 2 devices with the same name but different IDs. 

Until the problem is remedied upstream (in Chrome), there isn't much I can do... I filed a [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=965125) with the Chromium team.

**Comment by djipco** [comment] 2019-05-20 19:05
>I had a short look to the headless tests, giving two identical input names and midi-test it seems to give the identical driver id out

The `jzz` module should assign different IDs. This would need to be fixed on their end.

**Comment by djipco** [comment] 2019-05-21 13:29
@tom-cartwright As you can see in the [Chromium bug tracker ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=965125#c3), this issue has been fixed in the new Windows Runtime MIDI API. However, this runtime is not yet enabled by default in Chromium/Chrome. To activate it, you can paste this in the address bar and select "Enabled" from the drop-down menu:

```chrome://flags#use-winrt-midi-api```

Obviously, this is not a perfect solution but it seems to be the state of affairs on Windows 10 for now. Since there isn't much I can do, I will close this issue.

**Closed by djipco** 2019-05-21 13:29 UTC
Labels: upstream

**Comment by tom-cartwright** [comment] 2019-05-21 13:36
@djipco @TimSusa  Thanks for your work on this and apologies for my lack of comms!

Appreciate the workaround, I'll keep my eye on the sate of Chrome going forward.
