### ISSUE TITLE
Next.js and Firefox aren't recognizing that midi isn't supported.

### ISSUE THREAD

**Issue by glend1** [djipco/webmidi#209] opened 2022-01-07 14:34 UTC
I am running a Next.js server and have the following on a page;

````
useEffect(() => {
    WebMidi
    .enable()
    .then(() => {})
    .catch(err => alert(err));
}, [])
````
when i try this in firefox the alert is never shown even though midi isn't supported by default.

I've looked at the [docs](https://webmidijs.org/api/classes/WebMidi#enable) and there doesn't appear to be a way to override the default behaviour of autodetecting what platform webmidi is being run on.

**Comment by djipco** [comment] 2022-01-07 16:09
I'm not familiar with Next.js, but I can confirm that this bit of code (see below), works as it should in Firefox 95.0.2 (it displays the alert):

```js
WebMidi
  .enable()
  .then(() => {})
  .catch(err => alert(err));
```
So, something else is at play here. I'm not sure what `useEffect()` does in Next.js but it seems to prevent the alert from displaying.

Regarding auto-detection, I'm not sure what you would want to deactivate. If the Web MIDI API is not available, WEBMIDI.js is useless. In fact, the library does not "detect" anything. It just tries to call `requestMIDIAccess()` and throws an error if it's not there. 

If you want, you can check for support before calling `enable()` like so:

```js
if (!WebMidi.supported) alert("MIDI not supported!");
```

**Comment by glend1** [comment] 2022-01-07 16:14
Your right `alert(}` doesn't work in a next environment . `window.alert()` will.

but regardless, an error isn't thrown. I would like the ability to switch between node webmidi and browser webmidi.

**Comment by djipco** [comment] 2022-01-07 16:22
> but regardless, an error isn't thrown. 

If, instead of displaying an alert, you log a message to the console, it does not show up?

> I would like the ability to switch between node webmidi and browser webmidi.

Can you provide a little more info? This is the first time somebody requests that. Are you in an environment such as Electron or NW.js ?

**Comment by glend1** [comment] 2022-01-07 16:32
> If, instead of displaying an alert, you log a message to the console, it does not show up?
it doesn't
>Can you provide a little more info? This is the first time somebody requests that. Are you in an environment such as Electron or NW.js ?
I use next.js its a react framework it has frontend and backend(node) implimentations. I want to be be able to use webmidi in a browser, but webmidi is detecting(i think) im running on node and therefore no error is happening.

`useEffect()` runs javascript in the browser.
so I don't want node support because events can't be sent from a browser back to the node server to be processed there.

**Comment by djipco** [comment] 2022-01-07 16:51
The message should show up in the console. It does when I try the plain vanilla version. Again, I think something else is at play here.

> I want to be be able to use webmidi in a browser, but webmidi is detecting(i think) im running on node and therefore no error is happening.

When a framework uses Webpack (which I believe Next.js does), Webpack will use the CommonJS (Node) version of libraries by default. In this case, I have to figure out if we are actually on Node.js or if we are in a bundle prepared by Webpack for the browser. This is why you are getting a warning in the console (issue #210).

Perhaps it would be easier in your scenario to simply use the IIFE version ? I'm not sure I fully grasp the implications here...

**Comment by glend1** [comment] 2022-01-07 17:17
IIFE versions of webmidi?

**Comment by djipco** [comment] 2022-01-07 17:39
Yes

**Comment by glend1** [comment] 2022-01-07 17:41
you just want me to wrap my code in `(code)()`?

**Comment by djipco** [comment] 2022-01-07 17:44
No.
What I'm saying is that you could use the IIFE version of WebMidi when you are targeting the browser. It's available in `/dist/iife/webmidi.iife.js`.

**Comment by djipco** [comment] 2022-01-07 17:49
In fact, only the CommonJS version of the library ever tries to load the `jzz` plugin if it detects that the code is being run in Node.js. 

The IIFE and ESM versions do not ever try to load any external modules (because they don't need to).

**Comment by glend1** [comment] 2022-01-07 17:51
`Module not found: Package path ./dist/iife/webmidi.iife is not exported from package E:\node_modules\webmidi (see exports field in E:\node_modules\webmidi\package.json)`

**Comment by djipco** [comment] 2022-01-07 17:53
Since it's IIFE, you would have to link it from the HTML page directly.

**Comment by djipco** [comment] 2022-01-11 00:11
My understanding is that this problem is actually the same as the one described in issue #210. So, I'm going to close this one and will be tracking progress on the other one.

**Closed by djipco** 2022-01-11 00:11 UTC
