### ISSUE TITLE
WebMidi and NodeJS/VUE

### ISSUE THREAD

**Issue by henriquegmatos** [djipco/webmidi#120] opened 2020-08-14 01:06 UTC
Hello Dear,

I'm trying to import WebMidi into VUE following the same idea suggested using the file webmidi.d.ts on issue #55  

I'm doing tests using the Nodejs + VUE component model.

I'm having an error message from inside the webmidi.d.ts file. Any idea how to solve?

A testing VUEJS code
----------------
```

<template>

    <div></div>

</template>


<script>
import {webmidi} from '../webmidi/webmidi.d.ts';
export default {
    mounted () {
          webmidi.enable (function (err) {
                 if (err) console.log ("An error occurred", err);
                webmidi.outputs [0] .playNote ("C3");
            });
     }
  }

</script>

<style> </style>
```
------------------------------------------

 Received Error
-----------------------

Failed to compile.

./src/webmidi/webmidi.d.ts
Module Error (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token, expected ","

   5 |
   6 | / ** All Input events extend this base event. * /
> 7 | export interface InputEventBase <T extends keyof InputEvents> {
     | ^
   8 | / ** The Input that triggered the event. * /
   9 | target: Input
  10 | at src / webmidi / webmidi.d.ts: 7: 35:
   5 |
   6 | / ** All Input events extend this base event. * /
> 7 | export interface InputEventBase <T extends keyof InputEvents> {
     | ^
   8 | / ** The Input that triggered the event. * /
   9 | target: Input
  10 |

1 error found.

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref- -0-0! ./ node_modules / vue-loader / lib ?? vue-loader-options! ./ src / components / GetHardware.vue? Vue & type = script & lang = js & 8: 0-50 18: 4-11 20: 6 -13
 @ ./src/components/GetHardware.vue?vue&type=script&lang=js&
 @ ./src/components/GetHardware.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref- -0-0! ./ node_modules / vue-loader / lib ?? vue-loader-options! ./ src / App.vue? Vue & type = script & lang = js &
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack) -dev-server / client? http: //192.168.90.80: 8080 & sockPath = / sockjs-node (webpack) /hot/dev-server.js ./src/main.js

 error in ./src/webmidi/webmidi.d.ts

Module parse failed: Unexpected token (7: 7)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
|
| / ** All Input events extend this base event. * /
> export interface InputEventBase <T extends keyof InputEvents> {
| / ** The Input that triggered the event. * /
| target: Input

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref- -0-0! ./ node_modules / vue-loader / lib ?? vue-loader-options! ./ src / components / GetHardware.vue? Vue & type = script & lang = js & 8: 0-50 18: 4-11 20: 6 -13
 @ ./src/components/GetHardware.vue?vue&type=script&lang=js&
 @ ./src/components/GetHardware.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref- -0-0! ./ node_modules / vue-loader / lib ?? vue-loader-options! ./ src / App.vue? Vue & type = script & lang = js &
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack) -dev-server / client? http: //192.168.90.80: 8080 & sockPath = / sockjs-node (webpack) /hot/dev-server.js ./src/main.js

-------------------------
Thank you.
--------------

**Comment by TimSusa** [comment] 2020-08-14 09:12
Hey, 

you seem to import the typescript file, which is simply wrong. Please import as it is suggested in the docs:

``` 
import WebMidi from "webmidi"; 
```

**Comment by henriquegmatos** [comment] 2020-08-14 15:07
Hello Tim,

Thank you.

The point is I was using the WebMidi 2.5.1.  I try all as posible combination to import into the component but without success.

Right now  I started to try with WebMidi 3.0.0-Alpha2.

I installed it with  'npm install webmidi@next --save' into the project.

But a received a new message below from npm run serve comand to start a VUE develop enviroment 

 ERROR  Failed to compile with 1 errors                      
This dependency was not found:
* perf_hooks in ./node_modules/webmidi/dist/webmidi.esm.min.js
To install it, you can run: npm install --save perf_hooks

After that I installed  this dependence using exactly the sugested command:  'npm install --save perf-hooks'

After try 'npm run serve' again,  I received again the same dependence message.

I am facing the problem rigth now. 
 
Thank you again.

**Comment by djipco** [comment] 2020-08-16 14:04
Unfortunately, I know nothing about Vue.js. However, as @TimSusa mentioned, you shouldn't be importing the TypeScript definition file (`.d.ts`). Did you try simply importing `webmidi.min.js`?

**Comment by henriquegmatos** [comment] 2020-08-16 16:03
Hello.

Now I was really lost with your question.

I'm using the package you downloaded using the npm install webmidi @ next command with the intention of getting version 3.0.0-Alpha2.

Within this package there is no webmidi.d.ts file that you mentioned.

I copied the node_modules / webmidi folder into myproject / public / webmidi project folder
 
from there I am using the command:

import {WebMidi} from "./public/webmidi/dist/webmidi.esm.js"

Because I understood that the browser needs to access this link, since the webmidi is a module that needs to be executed on the client side.

wouldn't this be the way?

greetings.

**Comment by henriquegmatos** [comment] 2020-08-16 16:47
Completing my previous message.

I managed to make Vue work as an ESM module. However, I had to make some adjustments to the webmidi.esm.js file as shown below.


// replacement 1

`
for (let cm in wm.MIDI_CHANNEL_MODE_MESSAGES) {
      if (
// changed from: wm.MIDI_CHANNEL_MODE_MESSAGES.hasOwnProperty (cm) &&

// to:
Object.MIDI_CHANNEL_MODE_MESSAGES.hasOwnProperty.call (wm, cm) &&
        number === wm.MIDI_CHANNEL_MODE_MESSAGES [cm]
      ) {
        return cm;
      }
    }
`

// replacement 2
`
for (let cc in wm.MIDI_CONTROL_CHANGE_MESSAGES) {
      if (

// changed from: wm.MIDI_CONTROL_CHANGE_MESSAGES.hasOwnProperty (cc) &&
        
// to:
Object.MIDI_CONTROL_CHANGE_MESSAGES.hasOwnProperty.call (wm, cc) &&
  
        number === wm.MIDI_CONTROL_CHANGE_MESSAGES [cc]
      ) {
        return cc;
      }
}
`
// modification 3

`
// line below just commented waiting for a definitive solution for Vue Bundle
 // global.performance = require ("perf_hooks"). performance;

`
WebMidi EJS works perfectly without warning when imported into a server-side application. However, when loaded on the browser side the perf_hooks component is not found.

With these 3 modifications, WebMidi worked in a Vue application without a problem, even with the warning that appears on the console of the vue server. See warning below
-
 WARNING Compiled with 1 warnings 11:34:14 AM
 warning in ./node_modules/jazz-midi/index.js

Critical dependency: the request of a dependency is an expression
-

Either way the application works so far. I have already tested the commands successfully:

-WebMidi.enable ({sysex: true})
-WebMidi.inputs
-WebMidi.outputs
-WebMidi.playNote
-WebMidi.sendSysex

Below is a test code working ok even with the perf_hooks alert
`
<template>
<p> Hello WebMidi </p>
</template>

<script>
import {WebMidi} from "../public/webmidi/dist/webmidi.esm.js"
export default {

  mounted () {// Component life-cycle method
        WebMidi
          .enable ({sysex: true})
          .then (onEnabled)
          .catch (err => alert (err));

        function onEnabled () {
        console.log ('**** METRONOMO ****')
         let synth = WebMidi.getOutputByName ("Yamaha MOXF6 / MOXF8-1")
         synth.sendSysex (0x43, [0x10, 0x7f, 0x1c, 0x00, 0x00, 0x05, 0x00, 0x03])
        }
 }
</script>
`

Thanks

**Comment by djipco** [comment] 2020-08-16 18:46
I'm glad to know you got it working and would like to thank you for reporting your findings. Give me some time to review your modifications and I'll get back to you.

**Comment by djipco** [comment] 2020-08-17 03:33
There's a lot to unpack... Let's start by the last part. The `perf_hooks.performance`  module should only be required when the project is launched inside Node.js and never in the browser (where it is available by default). This makes me think that, for some reason, when you launch the project in the browser through Vue, the library thinks that it's environment is Node.js. 

Can you run the project in the browser and check the value of `WebMidi.isNode` by printing it to the console? What do you get? If the value is `true` when running in the browser, it means something is wrong with my Node.js detection function.

**Comment by henriquegmatos** [comment] 2020-08-17 13:25
Running as you ask the result is false.

`          WebMidi.enable( {sysex:true} ).then(() => console.log('Node = '+WebMidi.isNode))`

regards

**Comment by djipco** [comment] 2020-10-11 21:04
I had some time today to take another look at this issue. The first and second replacements you suggest are incorrect. There are no `MIDI_CONTROL_CHANGE_MESSAGES` or `MIDI_CHANNEL_MODE_MESSAGES ` in the native `Object` object. 

So when you try to use `Object.MIDI_CHANNEL_MODE_MESSAGES.hasOwnProperty.call (wm, cm)` in a condition, it probably throws the following error: 

```
VM213:1 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
```

Why this makes your code work is hard to say without seeing the actual error and ensuing behaviour. One thing is for sure though: the `getChannelModeByNumber()` and `getChannelModeByNumber()` of the `InputChannel()` object are disabled by the changes you made (which is a relatively small problem).

**Comment by djipco** [comment] 2020-10-11 21:10
My intuition tells me there's a problem in VUE with circular dependencies. The `WebMidi` object imports `ChannelInput` and `ChannelInput` imports `WebMidi`. But maybe it's something else... It's hard to say without having the actual problematic code to play with...

**Comment by TimSusa** [comment] 2020-10-18 03:01
My intuition tells me, that this discussion is out of scope. So common guys, VUE is just like React. A Framework for the View and it has completely nothing to do with kind of importing modules. You should be able to use webmidi here the same as it is with react or svelte or vanilla js. Maybe consider what your bundler does? Please check out my Example Project :

https://github.com/TimSusa/vue-webmidi-example

**Comment by TimSusa** [comment] 2020-10-18 14:30
Hey, 

Just some suggestions:

> Below is a test code working ok even with the perf_hooks alert
-> **_Sry, I do not get your point concerning perf_hooks._** 
> 
> ```
> <template>
> <p> Hello WebMidi </p>
> </template>
> 
> <script>
> import {WebMidi} from "../public/webmidi/dist/webmidi.esm.js" 
**_-> why would you use that fishy import? Just npm i webmidi and  import Webmidi from 'webmidi_**
> export default {
> 
>   mounted () {// Component life-cycle method
>         WebMidi
>           .enable ({sysex: true}) 
**_-> Webmidi expects a function here_**
>           .then (onEnabled) 
**_-> No Promise can be used here, as far as I know_**
>           .catch (err => alert (err)); 
-> No Promise, No Catch can be used here, as far as I know
> 
>         function onEnabled () { 
**_-> Why just use WebMidi.enable(onEnabled)?_**
>         console.log ('**** METRONOMO ****')
>          let synth = WebMidi.getOutputByName ("Yamaha MOXF6 / MOXF8-1")
>          synth.sendSysex (0x43, [0x10, 0x7f, 0x1c, 0x00, 0x00, 0x05, 0x00, 0x03])
>         }
>  }
> </script>
> ```
> 
> Thanks

**Comment by djipco** [comment] 2020-10-18 14:42
@TimSusa, thank you so much for the Vue.js example. I intend to have a folder of such starter examples for different environments in v3.

@henriquegmatos, can you confirm this works for you?

**Comment by djipco** [comment] 2020-10-18 14:44
@TimSusa Regarding you second message, I believe he is using [v3 alpha](https://github.com/djipco/webmidi/tree/develop) (hence the promise).

**Comment by henriquegmatos** [comment] 2020-10-19 15:33
@TimSusa 
Thank you very much for the example.  It is work ok with webmidi 2.5 but I am using  3.0.0-alfa-2.   

After testing with your example with 2.5 I upgraded to version 3.0.0 of webmidi and got the problem with perf_hooks and the compilation could not be completed.

```
Failed to compile.

./node_modules/webmidi/dist/webmidi.esm.min.js
Module not found: Error: Can't resolve 'perf_hooks' in '/root/Projetos-Nodejs/testdjipco/node_modules/webmidi/dist'
```
It is likely that you also get the same error message if you only update the component to version 3.0.0

best regards

**Comment by henriquegmatos** [comment] 2020-10-19 15:44
@djipco Hello, how are you?

Tim's example is perfect for getting the hook_perfs error using version 3.0.0 of Webmidi

The 3.0.0 documentation describes the installation that is not working for me.

I installed Webmidi 3.0.0 with the command npm i webmidi @ next successfully. However, npm installs the webmidi.esm.js file in the ./node_modules/webmidi/dist folder

so the command described in the documentation does not find it

```
// script tag
<script src = "node_modules/dist/webmidi.iife.js"> </script>

// CommonJS require
const {WebMidi} = require ("webmidi");

// ES module import
import {WebMidi} from "node_modules/dist/webmidi.esm.js";
```
I am looking forward to getting a complete example using version 3.0.0 in Vue with the import command. For now I'm using Script tag and I had to make those changes described in the previous messages

Thank you very much

**Comment by djipco** [comment] 2020-10-28 00:25
You are right. The paths mentioned in the `README.md` file were incorrect. This has now been fixed. Thank you for reporting it.

**Comment by djipco** [comment] 2020-10-28 01:55
I finally had some time to look at this. I used the example from @TimSusa to replicate the problem with v3.0.0. The issue first surfaces when building the Vue.js project:

```
This dependency was not found:

* perf_hooks in ./node_modules/webmidi/dist/webmidi.esm.min.js

To install it, you can run: npm install --save perf_hooks
```

I believe this error is reported by webpack which cannot find the `perf_hooks` Node.js module. This does not make much sense since `perf_hooks` has been a native, built in, module since Node.js v8.x. 

Some people reported that you can use this webpack config (below) to prevent it from trying to import native modules (I have not tested that):

```javascript
node: {
  fs: "empty",
  dgram: 'empty',
  net: 'empty',
  tls: 'empty',
  perf_hooks: 'empty' // <-- I guess we could add that
}
```
I guess the Vue.js team should add `perf_hooks` to the list of ignored native modules to make sure the bogus webpack error does not get triggered. In any case, I'm now quite confident that the problem is not with WebMidi.js.

In fact, you can comment out the `perf_hooks` module from `webmidi.esm.min.js` to make the error go away (this module is not needed in the browser):

```javascript
this._octaveOffset=0,this.isNode&&(/*global.performance=require("perf_hooks").performance,*/global.navigator=require("jzz"))}
```
If you start from @TimSusa's example, you will need to change the import to this: 

```javascript
import {WebMidi} from 'webmidi'
```

By design, there is no default export in WebMidi.js so you need to add the curly brackets (this is in the `App.vue` file). Once you do that, WebMidi.js v3.x works fine inside Vue.js.

Where do we go from here? I guess you should contact the Vue.js team and ask them to add `perf_hooks` to the list of ignored native modules inside their webpack config file.

Hope this helps!

**Comment by djipco** [comment] 2020-10-28 02:04
Since the problem is not with WebMidi.js, I will close the issue. If you get the Vue.js team to fix the problem, let me know so I can create a working starter example for Vue.js.

**Closed by djipco** 2020-10-28 02:04 UTC
Labels: Type: dependency

**Comment by alanfrazier** [comment] 2021-01-28 03:45
WebMidi.js works fine with Vue.js.

1. Make a Vue.js project using the cli.
2. Add WebMidi.js as a dependency in package.json file and re-run npm install.
3. import WebMidi from 'webmidi.js'; // in the script section of every Vue file.
4. Voila?

**Comment by djipco** [comment] 2021-01-28 21:43
@alanfrazier Would you know why we received an error with perf_hooks in the example above?

**Comment by alanfrazier** [comment] 2021-01-28 22:30
To be perfectly candid, I have not been able to identify anything about what @henriquegmatos has been attempting to do.  If I read the thread correctly, he was unable to make 2.5.1 work -- largely from not importing it correctly -- and then he abandoned 2.5.1 for the 3.x version.  I have not attempted the 3.x version.

**Comment by djipco** [comment] 2021-01-29 01:49
Let's leave it that then. :-)
