### ISSUE TITLE
How to idiomatically stop playback?

### ISSUE THREAD

**Issue by habemus-papadum** [djipco/webmidi#52] opened 2018-12-05 15:56 UTC
Hi -- Suppose I schedule multiple playNote & stopNotes across various channels at future time points.  What is the best way to allow the user to abort the all scheduled events -- is it to disable and then reenable WebMidi? (I'm looking for a solution that is similar to what is possible with webaudio where it is not possible to cancel individual events (i think), but it is simple enough to stop all sound with one command, and then start over from scratch.   

thanks, nehal

**Comment by djipco** [comment] 2018-12-07 01:44
The official [Web MIDI API](https://www.w3.org/TR/webmidi/#midioutput-interface) standard does specify a `clear()` method on `Output` objects to do exactly what you require. However, it has not yet been implemented in Chrome. This means that, once a message has been sent to the MIDI subsystem, it is essentially out of reach, even if scheduled in the future.

If you'd like to see the `clear()` method implemented in Chrome, I invite you to [vote for this feature](https://bugs.chromium.org/p/chromium/issues/detail?id=471798) on Chromium's bug tracker.

Pending the implementation of the `clear()` method, the workaround is to use the [sendChannelMode()](http://djipco.github.io/webmidi/latest/classes/Output.html#method_sendChannelMode) method to send **allnotesoff** or **allsoundoff** messages to the device. This is not perfect, though, because it will shut off currently playing notes but will not prevent scheduled notes to start playing at a later time...

Here's an example of sending the **allnotesoff** message to all channels of the first output device:

```javascript
WebMidi.outputs[0].sendChannelMode("allnotesoff");
```
If you want to know more, there is a discussion of the issue [on the spec's GitHub](https://github.com/WebAudio/web-midi-api/issues/102).

I'm going to tag this as an enhancement so I don't forget about it. However, until `clear()` is implemented upstream, there isn't much I can do.

Hope this helps!

**Comment by habemus-papadum** [comment] 2018-12-07 12:46
Thanks -- I registered my vote on the bug tracker.  nehal

**Comment by djipco** [comment] 2019-04-05 16:24
I'm closing this but I added a reference to it in the [Enhancements](https://github.com/djipco/webmidi/wiki#enhancements) section of the wiki.

**Closed by djipco** 2019-04-05 16:24 UTC
Labels: enhancement

**Comment by Amsvartner** [comment] 2019-04-18 07:13
I've made a sequencer on my MIDI-controller, with 16 steps. Each button should light up for 1 second every 16 seconds. Using the "time" property ensures that the steps will all be performed on time (using setTimeout will causes irregular timing on GC or CPU load), however cancelling them is then impossible.  So if I want to stop the sequencer mid-loop, it will continue to run until the loop ends. 

How about having an internal queue that waits until the last minute with sending the commands to the MIDI-controller? Taking into consideration the possible lag time, so for example if I want a command to be executed on time "15000", it would wait until "14800" before actually sending it. That way you could clear all the commands easily. Of course, you will get a 200ms lag on it, so whatever is supposed to be executed within 200ms of the **clear()** will still be sent, but that's a reasonable trade-off I think. What's your thoughts on that?

**Comment by djipco** [comment] 2019-04-21 00:59
@Amsvartner I think this would work. However, considering that `clear()` is part of the spec and should be implemented at some point, I'm not sure it is wise to spend time on this.

In the meantime, maybe this could be implemented as a plugin that overrides the `send()` method. This way we can get rid of it once `clear()` becomes available natively.

**Comment by stevage** [comment] 2023-12-04 12:53
According to the [Chrome bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=471798) it is still not implemented in Chrom/ium, but is implemented in Firefox.

Is this library particularly dependent on Chrome? I normally use Firefox...

**Comment by djipco** [comment] 2023-12-11 19:02
> Is this library particularly dependent on Chrome? I normally use Firefox...

This library is not dependent on Chrome anymore than Firefox. However, when I try to use `clear()` in Firefox (the only browser that claims to support it), it does not seem to work (or does not work in the way I expected). I'm not sure if the problem is with Firefox or the spec itself. I [asked for clarifications](https://github.com/WebAudio/web-midi-api/issues/260) on the Web MIDI API repo.

**Comment by djipco** [comment] 2023-12-13 02:45
A member of the Firefox team just [confirmed](https://github.com/WebAudio/web-midi-api/issues/260#issuecomment-1851640996) that there is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1869483) with the Firefox implementation of the `clear()` method.
