### ISSUE TITLE
playNote with duration option isn't sending a stop note event

### ISSUE THREAD

**Issue by zischwartz** [djipco/webmidi#37] opened 2018-05-08 16:32 UTC
I'm having an issue where calling `playNote`  with the duration option as specified in the readme doesn't appear to send a stop note event. I'm using  [MIDI Monitor](https://www.snoize.com/MIDIMonitor/) to monitor the events.

When I run:
```js
midiOut.playNote("Gb2", 10, {duration: 2000, velocity: 0.25});
```

I only get the one Note On event, there's never a Note Off event:

```
12:23:27.458	To MIDI Monitor (Untitled)	Note On	1	F♯2	32
```

System info: chrome 66.0.3359.139 on mac os 10.13.4.

Thanks!

**Comment by cotejp** [comment] 2018-05-09 11:30
You are right but I can say with 100% confidence that it was working before. When I try it in Opera, it works fine. I'm guessing the problem is upstream in the Chromium codebase. I guess we will have to file a bug there...

**Comment by drbourbon** [comment] 2018-05-12 08:41
I can confirm the issue (Chrome 66.0.3359.139 on OSX)

**Comment by djipco** [comment] 2018-05-12 08:54
I just checked and there is indeed a [problem](https://bugs.chromium.org/p/chromium/issues/detail?id=835664) in the Chromium codebase. Version 66.0.3359.141 fixes the problem and should be available very soon.

I'll leave this issue open until it is confirmed to be working. If you guys can chime in when it works, that would be useful.

**Comment by djipco** [comment] 2018-06-18 18:36
This has been fixed in the Chromium codebase. Closing.

**Closed by djipco** 2018-06-18 18:36 UTC
Labels: upstream
